version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.2
    - 3.25.3
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
    - 3.25.3
  - dependency-name: ember-concurrency
    versions:
    - 2.0.1
    - 2.0.2
